name = "thingrtc"
type = "javascript"
workers_dev = true
usage_model = "bundled"
account_id = "fe1ba256beb0b83c5ddae18642f7ea98"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
    {name = "SIGNALLING_SERVER", class_name = "SignallingServer"},
    {name = "PAIRING_SERVER", class_name = "PairingServer"}
]

[env.production]
zone_id = "8ac5536289dd6d47714fd21fd93e3fc5"
route = "signalling.thingify.app/*"

# It appears that durable_objects config is not inherited from the top level, so
# we need to repeat it here.
[env.production.durable_objects]
bindings = [
    {name = "SIGNALLING_SERVER", class_name = "SignallingServer"},
    {name = "PAIRING_SERVER", class_name = "PairingServer"}
]
