name = "thingrtc"
type = "javascript"
workers_dev = true
usage_model = "bundled"
account_id = "fe1ba256beb0b83c5ddae18642f7ea98"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "RELAY", class_name = "WebsocketRelay"}]
